name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test

    - name: Build project
      run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      env:
        HOST: ${{ secrets.EC2_HOST }}
        USERNAME: ${{ secrets.EC2_USERNAME }}
        KEY: ${{ secrets.EC2_KEY }}
      run: |
        echo "Deploying to EC2 instance"
        echo "${{ secrets.KEY }}" > pearl-task.pem
        chmod 600 pearl-task.pem
        ssh -o StrictHostKeyChecking=no -i pearl-task.pem ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'bash -s' < ./deploy-script.sh
